### ISSUE TITLE
is it some hack for it

### ISSUE THREAD

**Issue by truthSeekr** [ncri/ajaxify_rails#17]
In requirments there is :
Your app doesn't use named anchors (#). Named anchors can't be correctly represented in the fallback hash based url scheme.

Is it some hack for it ?

**Comment by ncri** [comment]
You might be able to program your own solution in js, but you cannot use '#' in your url. I don't really think it's worth it. 

Actually these days I recommend to use Turbolinks instead of Ajaxify. It brings almost the same speed improvements and is easier to use and less intrusive than Ajaxify - and very well maintained.
